//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManagement.Persistence.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public string EntityName { get; set; }
        public string PrimaryKeyJson { get; set; }
        public string ChangeType { get; set; }
        public string BeforeJson { get; set; }
        public string AfterJson { get; set; }
        public int UserId { get; set; }
        public System.DateTime AuditDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
